### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sebffischer** [sebffischer/dotfiles#1]
High priority: 
* [x] Fix the project root bug
* [ ] Fix that the R console is not covered by the status line...
* [ ] Dont automatch ' if it is preceded by #
* [ ] Migrate the remaining keybindings and plugins
* [ ] How to insert a single open bracket / parenthesis / curly brace
* [ ] Don't accept suggestion with enter
* [ ] rename action
* [ ] Quarto code indentiation in code blocks 
* [ ] Cursor should be red

Nice to have:
* [ ] Ability to wrap selected text in a function call 
* [ ] Switch more seamlessly between the buffers
* [ ] Checkout all the plugins that come with LazyVim and learn them properly 
* [ ] Create Anki Cards for keybindings
* [ ] https://stackoverflow.com/questions/6053301/easier-way-to-navigate-between-vim-split-panes
* [ ] Telescope workspace symbols
* [ ] Delete an item from a vector in R
* [ ] Easily edit markdown tables
* [ ] Align stuff easily
* [ ] Replace word under cursor
* [ ] Neorg for my notes

Long term:
* [ ] Fuzzy matching for autcompletion. 
* [ ] Pasting code has the correct indentiation
* [ ] A "go to definition" version that allows to pick the buffer in which the file is being opened. 
* [ ] Marc a specific test and run it on a command
* [ ] Get a faster version of load_all that only reloads the buffers that have been altered (if devtools::load_all) does not already do this.
